#!/usr/bin/env bash
# ── MMPM Digital Ocean Droplet Setup ──────────────────────────────────────────
#
# Run this on a fresh Ubuntu 22.04 droplet as root.
#
# Prerequisites:
#   1. Create droplet (Ubuntu 22.04, $6/mo basic is fine)
#   2. Add A record: mmpm.co.nz → <droplet-ip>
#   3. Wait for DNS propagation (~5 min)
#   4. SSH in: ssh root@<droplet-ip>
#   5. Run: curl -sL <this-script-url> | bash
#      or: scp this script, then bash setup-droplet.sh
#
# What this script does:
#   1. Installs Docker + Docker Compose
#   2. Configures UFW firewall
#   3. Clones the MMPM repo
#   4. Generates strong API keys
#   5. Obtains Let's Encrypt certificate
#   6. Starts the production stack
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

DOMAIN="${MMPM_DOMAIN:-mmpm.co.nz}"
REPO="https://github.com/wjm2202/Parametric-Memory.git"
INSTALL_DIR="/opt/mmpm"

echo "═══════════════════════════════════════════════════"
echo "  MMPM Production Setup"
echo "  Domain: ${DOMAIN}"
echo "═══════════════════════════════════════════════════"

# ── 1. System updates ────────────────────────────────────────────────────────
echo "→ Updating system packages..."
apt-get update -qq && apt-get upgrade -y -qq

# ── 2. Install Docker ────────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
    echo "→ Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
else
    echo "→ Docker already installed"
fi

# Verify docker compose plugin
docker compose version >/dev/null 2>&1 || {
    echo "ERROR: docker compose plugin not found"
    exit 1
}

# ── 3. Firewall ──────────────────────────────────────────────────────────────
echo "→ Configuring UFW firewall..."
ufw --force reset >/dev/null
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp   comment "SSH"
ufw allow 80/tcp   comment "HTTP (redirect + ACME)"
ufw allow 443/tcp  comment "HTTPS"
ufw --force enable
echo "  Firewall: SSH + HTTP + HTTPS only"

# ── 4. Clone repo ───────────────────────────────────────────────────────────
if [[ -d "$INSTALL_DIR" ]]; then
    echo "→ Updating existing repo at ${INSTALL_DIR}..."
    cd "$INSTALL_DIR"
    git pull --ff-only
else
    echo "→ Cloning repo to ${INSTALL_DIR}..."
    git clone "$REPO" "$INSTALL_DIR"
    cd "$INSTALL_DIR"
fi

# ── 5. Generate API keys ────────────────────────────────────────────────────
ENV_FILE="${INSTALL_DIR}/.env.production"

if [[ ! -f "$ENV_FILE" ]]; then
    echo "→ Generating .env.production..."
    MMPM_API_KEY="mmk_$(openssl rand -hex 32)"
    MMPM_MCP_AUTH_KEY="mcp_$(openssl rand -hex 32)"

    cat > "$ENV_FILE" <<EOF
# ── MMPM Production Environment ──────────────────────────────────────────────
# Generated by setup-droplet.sh on $(date -Iseconds)
# KEEP THIS FILE SECRET. Do not commit to git.

NODE_ENV=production
MMPM_API_KEY=${MMPM_API_KEY}
MMPM_MCP_AUTH_KEY=${MMPM_MCP_AUTH_KEY}
MMPM_BLOCK_SECRET_ATOMS=1
SHARD_COUNT=4
EOF

    chmod 600 "$ENV_FILE"
    echo "  API Key:     ${MMPM_API_KEY}"
    echo "  MCP Auth Key: ${MMPM_MCP_AUTH_KEY}"
    echo ""
    echo "  ⚠️  SAVE THESE KEYS — they are in ${ENV_FILE}"
    echo ""
else
    echo "→ .env.production already exists, keeping existing keys"
    # Source existing keys
    set -a; source "$ENV_FILE"; set +a
fi

# ── 6. Obtain TLS certificate ───────────────────────────────────────────────
# Use standalone mode for initial cert (nginx not running yet)
if [[ ! -d "/etc/letsencrypt/live/${DOMAIN}" ]]; then
    echo "→ Obtaining Let's Encrypt certificate for ${DOMAIN}..."

    # Install certbot standalone
    apt-get install -y -qq certbot

    certbot certonly \
        --standalone \
        --non-interactive \
        --agree-tos \
        --email "${CERTBOT_EMAIL:-entityone22@gmail.com}" \
        -d "$DOMAIN"

    echo "  Certificate obtained"
else
    echo "→ Certificate already exists for ${DOMAIN}"
fi

# ── 7. Start production stack ────────────────────────────────────────────────
echo "→ Starting production stack..."

# Export keys for docker compose
export MMPM_API_KEY MMPM_MCP_AUTH_KEY

# Load .env.production
set -a; source "$ENV_FILE"; set +a

docker compose -f integrations/deploy/docker-compose.production.yml up -d --build

# Wait for health
echo "→ Waiting for services..."
for i in $(seq 1 30); do
    sleep 2
    if curl -sf "https://${DOMAIN}/health" >/dev/null 2>&1; then
        echo ""
        echo "═══════════════════════════════════════════════════"
        echo "  ✓ MMPM is live at https://${DOMAIN}"
        echo ""
        echo "  Health:  https://${DOMAIN}/health"
        echo "  MCP:     https://${DOMAIN}/mcp"
        echo "  API:     https://${DOMAIN}/atoms (requires Bearer token)"
        echo ""
        echo "  Cowork custom connector URL:"
        echo "    https://${DOMAIN}/mcp"
        echo ""
        echo "  API keys are in: ${ENV_FILE}"
        echo "═══════════════════════════════════════════════════"
        exit 0
    fi
    printf "."
done

echo ""
echo "WARNING: Services did not become healthy in 60s."
echo "Check logs: docker compose -f integrations/deploy/docker-compose.production.yml logs"
exit 1
