#!/usr/bin/env bash
# ── MMPM Digital Ocean Droplet Setup ──────────────────────────────────────────
#
# Run this on a fresh Ubuntu 22.04 droplet as root.
#
# Prerequisites:
#   1. Create droplet (Ubuntu 22.04, $6/mo basic is fine)
#   2. Add A record: mmpm.co.nz → <droplet-ip>
#   3. Wait for DNS propagation (~5 min)
#   4. SSH in: ssh root@<droplet-ip>
#   5. Clone the repo, cd into it, then run: bash integrations/deploy/setup-droplet.sh
#
# What this script does:
#   1. Installs Docker + Docker Compose
#   2. Configures UFW firewall (SSH + HTTP + HTTPS only)
#   3. Generates strong API keys (.env.production)
#   4. Obtains Let's Encrypt certificate
#   5. Starts the production stack (API + MCP + nginx + certbot)
#
# The MCP server includes OAuth2 (auto-approve, single-tenant).
# To connect Cowork: Settings → Connectors → Add custom → https://<domain>/mcp
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

DOMAIN="${MMPM_DOMAIN:-mmpm.co.nz}"
INSTALL_DIR="$(pwd)"
COMPOSE_FILE="integrations/deploy/docker-compose.production.yml"

# Verify we're in the repo root
if [[ ! -f "$COMPOSE_FILE" ]]; then
    echo "ERROR: Run this script from the repo root (where integrations/deploy/ exists)"
    echo "  cd ~/Parametric-Memory && bash integrations/deploy/setup-droplet.sh"
    exit 1
fi

echo "═══════════════════════════════════════════════════"
echo "  MMPM Production Setup"
echo "  Domain: ${DOMAIN}"
echo "  Dir:    ${INSTALL_DIR}"
echo "═══════════════════════════════════════════════════"

# ── 1. System updates ────────────────────────────────────────────────────────
echo "→ Updating system packages..."
apt-get update -qq && apt-get upgrade -y -qq

# ── 2. Install Docker ────────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
    echo "→ Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
else
    echo "→ Docker already installed"
fi

# Verify docker compose plugin
docker compose version >/dev/null 2>&1 || {
    echo "ERROR: docker compose plugin not found"
    exit 1
}

# ── 3. Firewall ──────────────────────────────────────────────────────────────
echo "→ Configuring UFW firewall..."
ufw --force reset >/dev/null
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp   comment "SSH"
ufw allow 80/tcp   comment "HTTP (redirect + ACME)"
ufw allow 443/tcp  comment "HTTPS"
ufw --force enable
echo "  Firewall: SSH + HTTP + HTTPS only"

# ── 4. Install certbot ──────────────────────────────────────────────────────
if ! command -v certbot &>/dev/null; then
    echo "→ Installing certbot..."
    apt-get install -y -qq certbot
else
    echo "→ certbot already installed"
fi

# ── 5. Generate API keys ────────────────────────────────────────────────────
ENV_FILE="${INSTALL_DIR}/.env.production"

if [[ ! -f "$ENV_FILE" ]]; then
    echo "→ Generating .env.production..."
    MMPM_API_KEY="mmk_$(openssl rand -hex 24)"
    MMPM_MCP_AUTH_KEY="mcp_$(openssl rand -hex 24)"

    cat > "$ENV_FILE" <<EOF
# ── MMPM Production Environment ──────────────────────────────────────────────
# Generated by setup-droplet.sh on $(date -Iseconds)
# KEEP THIS FILE SECRET. Do not commit to git.

# ── CORE ─────────────────────────────────────────────────────────────────────
NODE_ENV=production
PORT=3000
HOST=0.0.0.0
SHARD_COUNT=4
DB_BASE_PATH=/app/mmpm-db
LOG_LEVEL=info

# ── AUTHENTICATION ───────────────────────────────────────────────────────────
MMPM_API_KEY=${MMPM_API_KEY}
MMPM_MCP_AUTH_KEY=${MMPM_MCP_AUTH_KEY}
MMPM_OAUTH_ISSUER=https://${DOMAIN}
# Per-client named keys (optional). Example: MMPM_API_KEYS=mcp:key1,backup:key2
# MMPM_API_KEYS=

# ── SECURITY ─────────────────────────────────────────────────────────────────
MMPM_BLOCK_SECRET_ATOMS=1
MMPM_METRICS_PUBLIC=0

# ── WRITE POLICY & COMMIT TUNING ────────────────────────────────────────────
WRITE_POLICY=auto-write
MMPM_COMMIT_THRESHOLD=50
MMPM_COMMIT_INTERVAL_MS=5000
MMPM_PENDING_HIGH_WATER_MARK=500
MMPM_BACKPRESSURE_RETRY_AFTER_SEC=5

# ── INGESTION ────────────────────────────────────────────────────────────────
INGEST_BATCH_SIZE=100
INGEST_FLUSH_MS=1000
MMPM_ATOM_FILE=/app/seeds.json

# ── WAL & MARKOV ─────────────────────────────────────────────────────────────
MMPM_WAL_COMPACT_THRESHOLD_BYTES=10485760
MMPM_CONFIDENCE_HALF_LIFE_MS=604800000

# ── HLR (Half-Life Regression) ───────────────────────────────────────────────
MMPM_HLR_ENABLED=1
# MMPM_HLR_THETA=[0.1, 0.15, 0.3, 0.4]

# ── PPM (Prediction by Partial Matching) ─────────────────────────────────────
MMPM_PPM_ENABLED=1
MMPM_PPM_MAX_ORDER=3
MMPM_PPM_ESCAPE_THRESHOLD=0.3
MMPM_PPM_MAX_NODES=100000

# ── TIER ENGINE & CONSOLIDATION ──────────────────────────────────────────────
MMPM_TIER_ENABLED=1
MMPM_CONSOLIDATION_INTERVAL_MS=3600000
MMPM_CONSOLIDATION_REPLAY_TOP_N=50

# ── STDP ─────────────────────────────────────────────────────────────────────
# MMPM_STDP_TAU_MS=

# ── PRUNING ──────────────────────────────────────────────────────────────────
MMPM_PRUNE_ENABLED=0
MMPM_PRUNE_STALE_DAYS=30

# ── ACCESS LOG ───────────────────────────────────────────────────────────────
MMPM_ACCESS_LOG_ENABLED=1
MMPM_ACCESS_LOG_MAX=50000

# ── TTL ──────────────────────────────────────────────────────────────────────
MMPM_TTL_PROMOTION_THRESHOLD=3
MMPM_TTL_REAPER_INTERVAL_MS=60000

# ── AUDIT LOG ────────────────────────────────────────────────────────────────
MMPM_AUDIT_LOG_MAX_ENTRIES=1000

# ── GRAFANA ──────────────────────────────────────────────────────────────────
GF_SECURITY_ADMIN_USER=admin
GF_SECURITY_ADMIN_PASSWORD=admin
GF_AUTH_DISABLE_LOGIN_FORM=false
GF_AUTH_ANONYMOUS_ENABLED=false
GF_LOG_FILTERS=context:warn
EOF

    chmod 600 "$ENV_FILE"
    echo ""
    echo "  ┌─────────────────────────────────────────────────┐"
    echo "  │  SAVE THESE KEYS (stored in .env.production)    │"
    echo "  ├─────────────────────────────────────────────────┤"
    echo "  │  API Key:     ${MMPM_API_KEY}"
    echo "  │  MCP Auth:    ${MMPM_MCP_AUTH_KEY}"
    echo "  └─────────────────────────────────────────────────┘"
    echo ""
else
    echo "→ .env.production already exists — checking for missing vars..."

    # Merge new defaults into existing .env.production without overwriting
    # existing values. This makes upgrades seamless.
    _DEFAULTS=(
        "WRITE_POLICY=auto-write"
        "MMPM_COMMIT_THRESHOLD=50"
        "MMPM_COMMIT_INTERVAL_MS=5000"
        "MMPM_PENDING_HIGH_WATER_MARK=500"
        "MMPM_BACKPRESSURE_RETRY_AFTER_SEC=5"
        "INGEST_BATCH_SIZE=100"
        "INGEST_FLUSH_MS=1000"
        "MMPM_WAL_COMPACT_THRESHOLD_BYTES=10485760"
        "MMPM_CONFIDENCE_HALF_LIFE_MS=604800000"
        "MMPM_HLR_ENABLED=1"
        "MMPM_PPM_ENABLED=1"
        "MMPM_PPM_MAX_ORDER=3"
        "MMPM_PPM_ESCAPE_THRESHOLD=0.3"
        "MMPM_PPM_MAX_NODES=100000"
        "MMPM_TIER_ENABLED=1"
        "MMPM_CONSOLIDATION_INTERVAL_MS=3600000"
        "MMPM_CONSOLIDATION_REPLAY_TOP_N=50"
        "MMPM_PRUNE_ENABLED=0"
        "MMPM_PRUNE_STALE_DAYS=30"
        "MMPM_ACCESS_LOG_ENABLED=1"
        "MMPM_ACCESS_LOG_MAX=50000"
        "MMPM_TTL_PROMOTION_THRESHOLD=3"
        "MMPM_TTL_REAPER_INTERVAL_MS=60000"
        "MMPM_AUDIT_LOG_MAX_ENTRIES=1000"
        "MMPM_METRICS_PUBLIC=0"
        "LOG_LEVEL=info"
    )
    _ADDED=0
    for _DEF in "${_DEFAULTS[@]}"; do
        _KEY="${_DEF%%=*}"
        if ! grep -q "^${_KEY}=" "$ENV_FILE" 2>/dev/null; then
            echo "${_DEF}" >> "$ENV_FILE"
            ((_ADDED++)) || true
        fi
    done
    if [[ $_ADDED -gt 0 ]]; then
        echo "  Added ${_ADDED} new default vars to .env.production"
    else
        echo "  All vars present — no changes needed"
    fi
fi

# Source env for docker compose
set -a; source "$ENV_FILE"; set +a

# ── 6. Obtain TLS certificate ───────────────────────────────────────────────
# Use standalone mode for initial cert (nginx not running yet)
if [[ ! -d "/etc/letsencrypt/live/${DOMAIN}" ]]; then
    echo "→ Obtaining Let's Encrypt certificate for ${DOMAIN}..."

    # Stop anything on port 80 first
    docker compose -f "$COMPOSE_FILE" down 2>/dev/null || true

    certbot certonly \
        --standalone \
        --non-interactive \
        --agree-tos \
        --email "${CERTBOT_EMAIL:-entityone22@gmail.com}" \
        -d "$DOMAIN"

    echo "  Certificate obtained"
else
    echo "→ Certificate already exists for ${DOMAIN}"
fi

# ── 7. Start production stack ────────────────────────────────────────────────
echo "→ Building and starting production stack..."
docker compose -f "$COMPOSE_FILE" up -d --build

# Wait for health
echo "→ Waiting for services..."
for i in $(seq 1 30); do
    sleep 2
    if curl -sf "https://${DOMAIN}/health" >/dev/null 2>&1; then
        echo ""
        echo "═══════════════════════════════════════════════════"
        echo "  MMPM is live at https://${DOMAIN}"
        echo ""
        echo "  Endpoints:"
        echo "    Health:  https://${DOMAIN}/health"
        echo "    MCP:     https://${DOMAIN}/mcp"
        echo "    API:     https://${DOMAIN}/atoms (Bearer token)"
        echo "    OAuth:   https://${DOMAIN}/.well-known/oauth-authorization-server"
        echo ""
        echo "  Cowork setup:"
        echo "    Settings → Connectors → Add custom connector"
        echo "    URL: https://${DOMAIN}/mcp"
        echo "    (OAuth is automatic — just click Connect)"
        echo ""
        echo "  Keys:  ${ENV_FILE}"
        echo "═══════════════════════════════════════════════════"
        exit 0
    fi
    printf "."
done

echo ""
echo "WARNING: Services did not become healthy in 60s."
echo "Check logs: docker compose -f ${COMPOSE_FILE} logs"
exit 1
