#!/usr/bin/env bash
# ── MMPM Digital Ocean Droplet Setup ──────────────────────────────────────────
#
# Run this on a fresh Ubuntu 22.04 droplet as root.
#
# Prerequisites:
#   1. Create droplet (Ubuntu 22.04, $6/mo basic is fine)
#   2. Add A record: mmpm.co.nz → <droplet-ip>
#   3. Wait for DNS propagation (~5 min)
#   4. SSH in: ssh root@<droplet-ip>
#   5. Clone the repo, cd into it, then run: bash integrations/deploy/setup-droplet.sh
#
# What this script does:
#   1. Installs Docker + Docker Compose
#   2. Configures UFW firewall (SSH + HTTP + HTTPS only)
#   3. Generates strong API keys (.env.production)
#   4. Obtains Let's Encrypt certificate
#   5. Starts the production stack (API + MCP + nginx + certbot)
#
# The MCP server includes OAuth2 (auto-approve, single-tenant).
# To connect Cowork: Settings → Connectors → Add custom → https://<domain>/mcp
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

DOMAIN="${MMPM_DOMAIN:-mmpm.co.nz}"
INSTALL_DIR="$(pwd)"
COMPOSE_FILE="integrations/deploy/docker-compose.production.yml"

# Verify we're in the repo root
if [[ ! -f "$COMPOSE_FILE" ]]; then
    echo "ERROR: Run this script from the repo root (where integrations/deploy/ exists)"
    echo "  cd ~/Parametric-Memory && bash integrations/deploy/setup-droplet.sh"
    exit 1
fi

echo "═══════════════════════════════════════════════════"
echo "  MMPM Production Setup"
echo "  Domain: ${DOMAIN}"
echo "  Dir:    ${INSTALL_DIR}"
echo "═══════════════════════════════════════════════════"

# ── 1. System updates ────────────────────────────────────────────────────────
echo "→ Updating system packages..."
apt-get update -qq && apt-get upgrade -y -qq

# ── 2. Install Docker ────────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
    echo "→ Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
else
    echo "→ Docker already installed"
fi

# Verify docker compose plugin
docker compose version >/dev/null 2>&1 || {
    echo "ERROR: docker compose plugin not found"
    exit 1
}

# ── 3. Firewall ──────────────────────────────────────────────────────────────
echo "→ Configuring UFW firewall..."
ufw --force reset >/dev/null
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp   comment "SSH"
ufw allow 80/tcp   comment "HTTP (redirect + ACME)"
ufw allow 443/tcp  comment "HTTPS"
ufw --force enable
echo "  Firewall: SSH + HTTP + HTTPS only"

# ── 4. Install certbot ──────────────────────────────────────────────────────
if ! command -v certbot &>/dev/null; then
    echo "→ Installing certbot..."
    apt-get install -y -qq certbot
else
    echo "→ certbot already installed"
fi

# ── 5. Generate API keys ────────────────────────────────────────────────────
ENV_FILE="${INSTALL_DIR}/.env.production"

if [[ ! -f "$ENV_FILE" ]]; then
    echo "→ Generating .env.production..."
    MMPM_API_KEY="mmk_$(openssl rand -hex 24)"
    MMPM_MCP_AUTH_KEY="mcp_$(openssl rand -hex 24)"

    cat > "$ENV_FILE" <<EOF
# ── MMPM Production Environment ──────────────────────────────────────────────
# Generated by setup-droplet.sh on $(date -Iseconds)
# KEEP THIS FILE SECRET. Do not commit to git.

NODE_ENV=production
MMPM_API_KEY=${MMPM_API_KEY}
MMPM_MCP_AUTH_KEY=${MMPM_MCP_AUTH_KEY}
MMPM_OAUTH_ISSUER=https://${DOMAIN}
MMPM_BLOCK_SECRET_ATOMS=1
SHARD_COUNT=4
EOF

    chmod 600 "$ENV_FILE"
    echo ""
    echo "  ┌─────────────────────────────────────────────────┐"
    echo "  │  SAVE THESE KEYS (stored in .env.production)    │"
    echo "  ├─────────────────────────────────────────────────┤"
    echo "  │  API Key:     ${MMPM_API_KEY}"
    echo "  │  MCP Auth:    ${MMPM_MCP_AUTH_KEY}"
    echo "  └─────────────────────────────────────────────────┘"
    echo ""
else
    echo "→ .env.production already exists, keeping existing keys"
fi

# Source env for docker compose
set -a; source "$ENV_FILE"; set +a

# ── 6. Obtain TLS certificate ───────────────────────────────────────────────
# Use standalone mode for initial cert (nginx not running yet)
if [[ ! -d "/etc/letsencrypt/live/${DOMAIN}" ]]; then
    echo "→ Obtaining Let's Encrypt certificate for ${DOMAIN}..."

    # Stop anything on port 80 first
    docker compose -f "$COMPOSE_FILE" down 2>/dev/null || true

    certbot certonly \
        --standalone \
        --non-interactive \
        --agree-tos \
        --email "${CERTBOT_EMAIL:-entityone22@gmail.com}" \
        -d "$DOMAIN"

    echo "  Certificate obtained"
else
    echo "→ Certificate already exists for ${DOMAIN}"
fi

# ── 7. Start production stack ────────────────────────────────────────────────
echo "→ Building and starting production stack..."
docker compose -f "$COMPOSE_FILE" up -d --build

# Wait for health
echo "→ Waiting for services..."
for i in $(seq 1 30); do
    sleep 2
    if curl -sf "https://${DOMAIN}/health" >/dev/null 2>&1; then
        echo ""
        echo "═══════════════════════════════════════════════════"
        echo "  MMPM is live at https://${DOMAIN}"
        echo ""
        echo "  Endpoints:"
        echo "    Health:  https://${DOMAIN}/health"
        echo "    MCP:     https://${DOMAIN}/mcp"
        echo "    API:     https://${DOMAIN}/atoms (Bearer token)"
        echo "    OAuth:   https://${DOMAIN}/.well-known/oauth-authorization-server"
        echo ""
        echo "  Cowork setup:"
        echo "    Settings → Connectors → Add custom connector"
        echo "    URL: https://${DOMAIN}/mcp"
        echo "    (OAuth is automatic — just click Connect)"
        echo ""
        echo "  Keys:  ${ENV_FILE}"
        echo "═══════════════════════════════════════════════════"
        exit 0
    fi
    printf "."
done

echo ""
echo "WARNING: Services did not become healthy in 60s."
echo "Check logs: docker compose -f ${COMPOSE_FILE} logs"
exit 1
